name: Build and push Docker image and send tag as dispatch event 🚀

on:

  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - apps/treasures/**.kt
      - apps/treasures/**.kts
      - apps/treasures/**.xml
      - apps/treasures/Dockerfile

env:
  AWS_REGION: eu-west-1

  IAC_ENVIRONMENT: pirates-dev
  APP_NAME: treasures

  RECEIVER_REPOSITORY: oslokommune/pirates-iac

jobs:

  docker-build-push:

    # https://github.com/oslokommune/reusable-workflows/blob/main/.github/workflows/docker_build_push.yml
    name: Build and push Docker image
    uses: oslokommune/reusable-workflows/.github/workflows/docker_build_push.yml@main
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      # TODO: Remove this if you don't need temporary secrets for RUN instructions in your Dockerfile
      DOCKER_SECRETS: |
        GPR_USERNAME=${{ secrets.GPR_USERNAME }}
        GPR_ACCESS_TOKEN=${{ secrets.GPR_ACCESS_TOKEN }}
    with:
      environment: pirates-dev-ecr
      push: true
      region: eu-west-1
      ecr_repository_name: pirates-dev-treasures
      # TODO: Change or remove build args. `IMAGE_CREATED_DATETIME`, `IMAGE_VERSION` and `IMAGE_REVISION` are always added.
      build_args: |
        FELINE=cat
        DINOSAUR=stegosaurus


  dispatch:

    if: ${{ false }} # Initially disabled

    needs: docker-build-push

    runs-on: ubuntu-latest

    name: Trigger workflow in another repository 🛫

    steps:

      - name: Send dispatch event with image tag 🛫
        uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570 # v2.1.2
        with:
          token: ${{ secrets.PAT_ON_MACHINE_USER_FOR_IAC_DISPATCH }}
          repository: ${{ env.RECEIVER_REPOSITORY }}
          event-type: ${{ env.IAC_ENVIRONMENT }}-${{ env.APP_NAME }}-image-tag-update
          client-payload: >
            {
              "image_version": "${{ needs.docker-build-push.outputs.image_version }}",
              "sender_repository": "${{ github.repository }}",
              "sender_run_id": "${{ github.run_id }}",
              "sender_before_sha": "${{ github.event.before }}",
              "sender_after_sha": "${{ github.event.after }}"
            }


      - name: Write job summary
        env:
          # The workflow in another repository that will receive an event with the updated Docker image tag
          RECEIVER_WORKFLOW: ${{ env.APP_NAME }}-${{ env.IAC_ENVIRONMENT }}_receive_dispatch_event_and_commit_image_tag.yml
        run: |
          cat >> "$GITHUB_STEP_SUMMARY" <<EOF
          Repository dispatch event sent to [\`${{ env.RECEIVER_REPOSITORY }}\`](https://github.com/${{ env.RECEIVER_REPOSITORY }}/actions/workflows/${{ env.RECEIVER_WORKFLOW }}) with the following image version:

          \`\`\`text
          ${{ needs.docker-build-push.outputs.image_version }}
          \`\`\`

          This value can be used to find the image in the ECR repository in order to update [the ECS task container definition image](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_image).
          EOF
